{
 "title": "SMART",
 "tags": [ "system" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "SMART Health",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "smartprom_smart_passed{}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "smartprom_temperature_celsius_raw{}",
     "legendFormat": "{{instance}} {{drive}}"
    }
   ]
  },
  {
   "title": "Info Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartprom_temperature_celsius_raw{}"
    },
    {
     "expr": "smartprom_power_cycle_count_raw{}"
    },
    { "expr": "smartprom_power_on_hours_raw{}" }
   ]
  },
  {
   "title": "SAS Error Metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartprom_scsi_grown_defect_list{}"
    },
    {
     "expr": "smartprom_scsi_error_counter_log_read_total_uncorrected_errors{}"
    },
    {
     "expr": "smartprom_scsi_error_counter_log_write_total_uncorrected_errors{}"
    }
   ]
  },
  {
   "title": "Sata Error Metrics",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "smartprom_reallocated_sector_ct_raw{}"
    },
    {
     "expr": "smartprom_reported_uncorrect_raw{}"
    },
    {
     "expr": "smartprom_command_timeout_raw{}"
    },
    {
     "expr": "smartprom_current_pending_sector_raw{}"
    },
    {
     "expr": "smartprom_offline_uncorrectable_raw{}"
    }
   ]
  }
 ]
}